### ISSUE TITLE
希望能输入表情编号来调用表情

### ISSUE THREAD

**Issue by yi03** [lgc2333/koishi-plugin-memes-api#1]
比如现在如果我想使用5000兆表情的话，必须发 `meme generate 5000兆 我去 洛天依`，希望可以直接使用图片编号，如5000兆表情的编号是1，就发送 `meme generate 1 我去 洛天依` 这样就行。发送 `meme info 1` 就能看5000兆表情的信息。
谢谢大佬！

**Comment by lgc2333** [comment]
更新0.1.7版本
