### ISSUE TITLE
新版还是连不上2233

### ISSUE THREAD

**Issue by 315923876** [lgc2333/koishi-plugin-memes-api#4]
服务器已经成功启动，监听0.0.0.0:2233
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/3c20699f-e6dc-46e6-adc9-d0201b258308)
插件连接127.0.0.1:2233
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/28f4caa0-6177-4d83-9cb8-2b746ef9dc08)
日志显示协议不匹配，日志为debug等级，且meme控制台未收到任何连接请求（如图一）
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/f0db9e6c-5f83-4f5e-87ef-827307aa68dc)
测试2233端口是在局域网内可访问的
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/2b652f40-9a4c-48e9-b237-42b509ce7a2d)
当使用浏览器的时候也是可以正常访问并输出日志
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/410915f8-76b3-4574-b947-a2b861d005bf)

做了个测试，如果填写https协议，https://127.0.0.1:8081，则（web，不是meme）服务端是会收到响应的
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/7278b745-2b38-42f5-8f68-54292bd3d305)
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/726e5ce7-9605-4b47-a4d7-d5d3d0ed29f7)
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/cf573988-073b-493a-ae24-c2703eff1145)
但是如果填写http://127.0.0.1:8081，则web服务端不会收到响应。似乎是填写http协议的时候，插件会直接报错，不会发起请求？
版本信息，meme gen-api 版本0.18
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/4b354e64-8c09-4e31-9020-e48f046a783a)

**Comment by lgc2333** [comment]
有没有设置代理？

**Comment by 315923876** [comment]
> 有没有设置代理？

没有设置系统代理，没有设置koishi代理，虚拟网卡没有启用。
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/37d0fc7d-a172-4216-acd3-921a408b374f)
刚试了下如果写https：127.0.0.1:2233，meme服务端也会收到响应，http：127.0.0.1:2233是完全没有响应

**Comment by lgc2333** [comment]
真的好玄学😭 我也不知道什么情况，抱歉了

**Comment by 315923876** [comment]
> 真的好玄学😭 我也不知道什么情况，抱歉了

啊，好的好的，没事
![3U( BK(%L67XQ8KK$JR}~KH](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/d493b3db-5634-435c-8880-59cedfd623c7)

**Comment by ltxhhz** [comment]
没法复现
能否去掉敏感信息发一下你的 `koishi.yml`
顺便再运行一下
```bash
npm config get proxy
npm config get https-proxy
```
看看结果

---

最后可以在目录下试试重新安装
```bash
rm -force .\node_modules\koishi-plugin-memes-api
npm i
```

**Comment by Lipraty** [comment]
可以在 yarn dev script 中添加 `NODE_DEBUG=http` 来详细呈现请求并定位问题：
```jsonc
//your package.json
"dev": "cross-env NODE_DEBUG=http NODE_ENV=development koishi start -r esbuild-register -r yml-register --watch",
```

**Comment by 315923876** [comment]
> 没法复现 能否去掉敏感信息发一下你的 `koishi.yml` 顺便再运行一下
> 
> ```shell
> npm config get proxy
> npm config get https-proxy
> ```
> 
> 看看结果
> 
> 最后可以在目录下试试重新安装
> 
> ```shell
> rm -force .\node_modules\koishi-plugin-memes-api
> npm i
> ```

![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/35c5e142-a732-4ce0-8e14-8d4d05d65189)
好的，这个是运行结果。卸载指令不会用TAT，我在依赖管理和插件配置里面都删除了，然后重新安装没有解决问题。

koishi.yaml:
port: 5140
maxPort: 5149
plugins:
  group:basic:
    ~admin:
      $filter:
        $eq:
          - $: userId
          - '315923876'
    ~bind: {}
    commands:
      nh:
        name: /chat
        aliases:
          - rr-nh
          - '!!'
      nh.clear:
        name: nh/éç½®chat
      echo:
        aliases:
          - qd1
        config:
          authority: 5
      hangman:
        aliases:
          - çåè¯
      bingchat:
        name: /bing
      chathub.chat:
        aliases:
          - by
          - èå¤©
          - bing
      chathub.reset:
        name: chathub/éç½®by
      chathub:
        name: /è¾å¥âbyâ ä¸newbingèå¤©
      ping:
        config:
          authority: 5
      shutdown:
        config:
          authority: 5
      cmd:
        config:
          authority: 5
      status:
        aliases:
          - æµ·çæå ç¨
        config:
          authority: 0
      sysinfo:
        config:
          authority: 5
      systools:
        config:
          authority: 5
      test:
        config:
          hidden: true
      ip:
        aliases:
          - æµ·çæ
        config:
          authority: 0
      switch:
        options:
          help:
            authority: 0
        config:
          authority: 0
      ç®å¦:
        aliases:
          - æ±è§£
      è¿ä¸ªæä»¤æ¯å®éªæ§ç:
        name: æé»/è¿ä¸ªæä»¤æ¯å®éªæ§ç
      plugin:
        config:
          authority: 5
      plugin.uninstall:
        config:
          authority: 5
      plugin.install:
        config:
          authority: 5
      plugin.upgrade:
        config:
          authority: 5
      or:
        aliases:
          - éæ©
      allow:
        aliases:
          - å¯ä»¥
          - ä¸è½
    locales: {}
    ~rate-limit: {}
  group:console:
    analytics: {}
    console:
      open: true
    dataview: {}
    desktop:
      $if: env.KOISHI_AGENT?.includes('Desktop')
    explorer: {}
    logger: {}
    ~login: {}
    config: {}
    market:
      registry:
        endpoint: https://registry.npmmirror.com
      search:
        endpoint: https://registry.koishi.chat/index.json
    sandbox: {}
    puppeteer:js84dr: {}
  group:storage:
    database-sqlite: {}
    ~database-mysql: {}
    ~database-mongo: {}
    cache-database:fd446u: {}
    assets-local: {}
  group:adapter:
    adapter-onebot:
      selfId: '1057732618'
    ~adapter-discord: {}
    ~adapter-telegram: {}
    ~adapter-kook: {}
    ~adapter-lark: {}
    ~gocqhttp:
      signServer: https://captcha.koishi.xyz/sdk/dandelion/energy
  group:i35rh5:
    '@ifrank/xibao:31s3wf': {}
    status: {}
    hangman:ohpgbx: {}
    long:zumeh7: {}
    guess-number:jjocbe: {}
    crazy-thursday:sjopd3: {}
    chess:vjwjlc: {}
    ~rr-su-bing:q41bh7: {}
    ~glm-testbot:1a9vno: {}
    ~qianyu:575ao2: {}
    5k:mfc7m4: {}
    httpcat:xda51g: {}
    ~rr-su-chat:iqjap1:
      isGm: true
      isLoc: false
      maxLength: 10
      privateIntensifier: false
      $filter:
        $ne:
          - $: guildId
          - '917850900'
    offer-a-proposal:lcd626: {}
    ~music:828khc: {}
    ~send-as-image:hwr6el:
      length: 22
    ~th-tarot:je2wnx: {}
    reborn:9vvde7:
      $filter:
        $ne:
          - $: guildId
          - '679334621'
    ~kbot:b3u4an:
      superAdminQQ:
        - '315923876'
      KBotMusic:
        showWarning: true
        authority: 1
        enabled: true
      KBotTarot:
        enabled: true
    help: {}
    '@dingyi222666/chathub-newbing-adapter:dnq86b':
      chatConcurrentMaxSize: 3
      cookie: >-
        _U=xxxxxx
    systools:inarup:
      ipPublic: true
    i-ching-joker:8g6fi7: {}
    '@dingyi222666/chathub:bx0z50':
      isNickname: false
      allowPrivate: false
      allowAtReply: false
      outputMode: raw
      thinkingMessage: åå
      sendThinkingMessageTimeout: 1500
      isProxy: true
      isLog: true
      proxyAddress: http://127.0.0.1:10803
      $filter:
        $or:
          - $and:
              - $eq:
                  - $: guildId
                  - '917850900'
              - $eq:
                  - $: userId
                  - '315923876'
          - $and:
              - $eq:
                  - $: platform
                  - onebot
              - $ne:
                  - $: guildId
                  - '917850900'
    who-at-me:ttxl9r: {}
    ~open-pixiv:3s2n98:
      proxy: http://127.0.0.1:10803
      cookie: ''
    ~dialogue:4kd854: {}
    respondent:2srog9:
      rules:
        - regexp: true
          match: ^å¢é(?:ä¸é¶|å­é¶)?çåè¯$
          reply: æ¬¢è¿æ¸¸ç©çåè¯ï¼é»è²æ¯å­æ¯å¯¹ä½ç½®ä¸å¯¹ï¼ç»¿è²æ¯é½å¯¹ï¼ç°è²çæ¯é½ä¸å¯¹
    ba-plugin:x831ht: {}
    ~marry:y9yres: {}
    blackjack:gmejnm: {}
    cck:tp8rqw: {}
    ~tsugu-bangdream-bot:merlpq: {}
    '@yrchashao/or:mb1lmt': {}
    $filter:
      $or:
        - $eq:
            - $: guildId
            - '782504543'
        - $eq:
            - $: guildId
            - '392818288'
        - $eq:
            - $: guildId
            - '561796418'
        - $eq:
            - $: guildId
            - '917850900'
        - $eq:
            - $: platform
            - sandbox:eoqr70y75z
        - $eq:
            - $: guildId
            - '679334621'
        - $eq:
            - $: guildId
            - '638671301'
  group:sn7ctu:
    $collapsed: true
    ~imitate:zvjaut: {}
    $filter:
      $or:
        - $eq:
            - $: guildId
            - '638671301'
        - $eq:
            - $: guildId
            - '782504543'
        - $ne:
            - $: userId
            - '315923876'
  ~inspect:rj3t3u: {}
  ~verifier:1aqrsl:
    onGuildRequest: 5
  ~group-invite:qqquis:
    masterId: '315923876'
    rows:
      admin: true
      member: true
    official: '638671301'
  echo:z8cxb4:
    $filter:
      $eq:
        - $: userId
        - '315923876'
  schedule:h3o25r:
    $filter:
      $eq:
        - $: userId
        - '315923876'
  switch:tthw4j:
    $filter:
      $eq:
        - $: userId
        - '315923876'
  ~@loneyknight/findmovie:60v2sy: {}
  ~addmpp:8fv45s: {}
  ~@chronocat/launcher:jn7wu9: {}
  ~@chronocat/adapter:av0j91:
    token: xxxxxx
    chronoSendImageType: b
  downloads:pqdskw: {}
  ~red:ipmwkx:
    self: '1057732618'
    path: ws://127.0.0.1:5140/onebot
  memes-api:l85qdm: {}
host: 0.0.0.0

**Comment by 315923876** [comment]
> 可以在 yarn dev script 中添加 `NODE_DEBUG=http` 来详细呈现请求并定位问题：
> 
> ```js
> //package.json in your workspace root:
> "dev": "cross-env NODE_DEBUG=http NODE_ENV=development koishi start -r esbuild-register -r yml-register --watch",
> ```

![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/8fe31205-ac07-4813-b983-ae91aa9daade)
请问是这样子添加吗，我添加，保存，重启koishi之后，在启用插件好像没有输出新的日志
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/63ad3b35-5d9c-400a-aeac-11b2e98bef00)

**Comment by Lipraty** [comment]
草，原来是 KD。

那你在那个 `"start"` 中修改：

```jsonc
script: {
  "start": "koishi start NODE_DEBUG=http"
}
```

**Comment by 315923876** [comment]
> 草，原来是 KD。
> 
> 那你在那个 `"start"` 中修改：
> 
> ```js
> script: {
>   "start": "koishi start NODE_DEBUG=http"
> }
> ```
> 
> 前期可能会有大量的 registry 拉取刷屏，你可以先不启用该插件，等待 registry 拉取完毕后启动插件查看请求。

不好意思，我在修改了之后无法启动koishi控制台了，是我哪里改错了吗
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/19c508ce-5373-4eec-b487-055baeeb8bb6)
![image](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/3a75fd30-c72f-433c-a5aa-d499d51953c3)

**Comment by Lipraty** [comment]
![38f84264f45c10502cf745734c3c6134](https://github.com/lgc2333/koishi-plugin-memes-api/assets/18106422/a56d2aca-a313-44fe-95d7-b50eb85a1bf7)
看来 kd 是真的不适合调试...啥都砍掉了（）
你可以选择这样：

托盘右键图标 -> 打开数据文件夹 -> 打开 `instances\default\node_modules\koishi-plugin-memes-api` 文件夹，将里面所有文件打包压缩，顺便也将你的 memes 后端也打包发出来。

剩下的就是饼干佬去复现了，cc @lgc2333 （

**Comment by lgc2333** [comment]
🛐🛐🛐🛐🛐🛐

**Comment by lgc2333** [comment]
把这些东西发给我，我能复现出什么名堂来啊😭

**Comment by 315923876** [comment]
> ![38f84264f45c10502cf745734c3c6134](https://user-images.githubusercontent.com/18106422/253788367-a56d2aca-a313-44fe-95d7-b50eb85a1bf7.jpg) 看来 kd 是真的不适合调试...啥都砍掉了（） 你可以选择这样：
> 
> 托盘右键图标 -> 打开数据文件夹 -> 打开 `instances\default\node_modules\koishi-plugin-memes-api` 文件夹，将里面所有文件打包压缩，顺便也将你的 memes 后端也打包发出来。
> 
> 剩下的就是饼干佬去复现了，cc @lgc2333 （

算了，我的配置都是刚装好没改，可能是我系统环境有问题，哪天换台电脑试试好了
![`$BY9K3Q@ W VOZ$7N85{4](https://github.com/lgc2333/koishi-plugin-memes-api/assets/115673942/b965e070-127f-47b6-9cad-b1ed20f5cb5d)

**Comment by 315923876** [comment]
突然想起来我用超时空猫猫的时候也经常会报这个协议不匹配，发不了图，问别人也都说没有，应该是我自己的问题，哪天重装一下系统看看
