### ISSUE TITLE
使用原版memes触发指令时禁用报错

### ISSUE THREAD

**Issue by melinoe98** [lgc2333/koishi-plugin-memes-api#7]
原版memes触发指令使用起来很方便，误触发时更能带来无限惊喜
但是正常聊天中如果误触发时参数不对，就不会生成表情包而是出现报错信息，惊喜就变成了扫兴
因此希望能有一个使用原版memes触发指令时，如果参数错误则保持静默，不会出现报错信息的功能

**Comment by lgc2333** [comment]
https://github.com/lgc2333/koishi-plugin-memes-api/commit/1fcbf864091a8fbc014664975eeea4a2ba8c02e7

**Comment by melinoe98** [comment]
谢谢！
