### ISSUE TITLE
小火箭更新后，memes-api插件无法使用图片生成表情。

### ISSUE THREAD

**Issue by Neptune1990** [lgc2333/koishi-plugin-memes-api#8]
小火箭更新后，memes-api插件无法使用图片生成表情，貌似读不到自定义图片。可能需要更新插件

![ee0703aa93803015a9f4b7cedd42190b](https://github.com/lgc2333/koishi-plugin-memes-api/assets/107494041/a78aadfc-bfa2-40e6-8309-be04245adc3a)

System:
OS: Windows 10 10.0.19045
CPU: (20) x64 12th Gen Intel(R) Core™ i7-12700
Binaries:
Node: 20.3.1
Yarn: 4.0.1

Koishi:
Core: 4.16.4
Console: 5.25.5
Koishi Desktop: 1.0.0

"@koishijs/plugin-admin": "2.0.0-beta.2",
"@koishijs/plugin-analytics": "2.0.6",
"@koishijs/plugin-auth": "4.1.6",
"@koishijs/plugin-bind": "1.5.1",
"@koishijs/plugin-callme": "1.3.3",
"@koishijs/plugin-commands": "3.4.7",
"@koishijs/plugin-config": "2.8.2",
"@koishijs/plugin-console": "5.25.5",
"@koishijs/plugin-database-mysql": "5.7.5",
"@koishijs/plugin-echo": "2.2.5",
"@koishijs/plugin-explorer": "1.5.0",
"@koishijs/plugin-help": "2.4.3",
"@koishijs/plugin-insight": "3.4.5",
"@koishijs/plugin-inspect": "1.1.3",
"@koishijs/plugin-locales": "2.5.2",
"@koishijs/plugin-logger": "2.6.5",
"@koishijs/plugin-market": "2.8.3",
"@koishijs/plugin-sandbox": "3.2.4",
"@koishijs/plugin-server": "3.1.3",
"@koishijs/plugin-status": "7.4.6",
"koishi": "4.16.4",
"koishi-plugin-adapter-red": "2.9.0",

**Comment by lgc2333** [comment]
没有用过red适配器，感觉可能是red适配器传过来的图片url不对

**Comment by Neptune1990** [comment]
red之前一直可用，最近koishi有较大的更新，就用不了。

**Comment by araea** [comment]
# 补充：
Koishi v4.16.4 更新之后更改了 \<image> 和 \<url> 标签，在最新的 Koishi 环境下，插件获取不到图片。

## 参考链接：
1. [Koishi 4.16.4 更新日志 - 官方发布 - Koishi Forum](https://forum.koishi.xyz/t/topic/6406)
2. [获取用户发送的图片 - 交流讨论 - Koishi Forum](https://forum.koishi.xyz/t/topic/6421/2)

**Comment by lgc2333** [comment]
好的，近期找时间修复（最近几天都在摸鱼玩mc）

**Comment by Liki4** [comment]
#10
