### ISSUE TITLE
请求改进逻辑

### ISSUE THREAD

**Issue by logier** [lgc2333/koishi-plugin-memes-api#9]
1.没有目标对象时依然会直接触发，并使用指令发送者头像。比如：发送 “摸” 而不是“摸 自己” 的时候就会启动，容易误触发。
2.“启动”因为前面需要加词，例如 元神启动 ，这就会导致聊天时出现 “你必须要这样启动”这样的句子时就会触发。
3. 当发送的meme 不需要头像而是需要文字时，因为没有没有文字 ，同时又快捷触发，就会提示确实文字，容易误触发。

**Comment by araea** [comment]
# 我完全认同楼主提到的问题。

## 当前插件存在一些易误触发的情况，比如：

- ### 在没有明确目标对象的情况下触发、需要特定词语前缀等问题。

- ### 特别是在发送 meme 时可能会引发误触发。

>## 期待插件作者能够尽快更新插件以解决这些问题，让用户体验更加顺畅。

**Comment by lgc2333** [comment]
关于单图片表情容易误触发，这个确实需要改进；
快捷指令误触发时的报错其实可以禁用（#7 已实现）（难道仅开启 `slientShortcut` 的情况下我忘掉忽略这个了？）；
关于指令偶尔不响应，这个以我的能力实在没法排查出原因，抱歉

**Comment by lgc2333** [comment]
https://github.com/lgc2333/koishi-plugin-memes-api?tab=readme-ov-file#0113
